# Generated by Django 5.1.2 on 2026-03-12 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toll', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='vehiclelog',
            new_name='toll_vehicl_timesta_b7099b_idx',
            old_name='toll_vehicl_timesta_9c3fbd_idx',
        ),
        migrations.RenameIndex(
            model_name='vehiclelog',
            new_name='toll_vehicl_vehicle_92e762_idx',
            old_name='toll_vehicl_vehicle_046a1d_idx',
        ),
        migrations.RenameIndex(
            model_name='vehiclelog',
            new_name='toll_vehicl_booth_i_e5a5fb_idx',
            old_name='toll_vehicl_booth__b1b081_idx',
        ),
    ]
