# Generated by Django 6.0.3 on 2026-03-12 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toll', '0003_populate_vehicle_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoupload',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
